### ISSUE TITLE
Is the code of IDOL ready for open source?

### ISSUE THREAD

**Issue by xiangyudxy** [KlabCMU/learned-map-prior#1]
Hello, I found that the IDOL was used when comparing the results. Is the code of IDOL ready for open source?

**Comment by karnikram** [comment]
Hi, thank you for your interest.

IDOL has licensing issues unfortunately and is unlikely to be released soon by its authors.

However, for our work, IDOL is not a strong requirement and any odometry algorithm (RoNIN, wheel odometry) would work.

**Comment by xiangyudxy** [comment]
> Hi, thank you for your interest.
> 
> IDOL has licensing issues unfortunately and is unlikely to be released soon by its authors.
> 
> However, for our work, IDOL is not a strong requirement and any odometry algorithm (RoNIN, wheel odometry) would work.

Thanks for your answer!
